name: Build and Sign Extension

on:
  push:
    branches:
      - gh-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - run: npm install
      - run: npm run test:unit
      - run: npm run build

      - uses: actions/cache@v3
        with:
          path: |
            artifacts
            dist
          key: ${{ runner.os }}-${{ github.sha }}

  sign:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            artifacts
            dist
          key: ${{ runner.os }}-${{ github.sha }}

      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: ${{ secrets.FIREFOX_ADDON_UUID }}
          xpi: artifacts/bookmark-power-pack-v1.0.1-production.zip
          manifest: dist/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
